spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hpu
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    
  
  
    druid:
      aop-patterns:
      - com.atgui.admin.*  # 监控SpringBean
      filters: stat,wall # 底层开启功能 stat(sql 监控)      wall(防火墙)
      
      stat-view-servlet:  # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
        
      web-stat-filter:  # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        
      filter:   
        stat:  # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
 
# 事务          
  dao:
    exceptiontranslation:
      enabled: false
   
  # 配置redis
  redis:
    host: 127.0.0.1 #Redis 服务器地址
    port: 6379  #Redis 服务器连接端口
    database: 0  #Redis 数据库索引( 默认为0)
    timeout: 1800000 #连接超时时间 (毫秒)
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数 (使用负数表示没有限制)
        max-wait: -1 # 最大阻塞等待时间
        max-idle: 5  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    client-type: jedis 
    
    
# type : mybatis

mybatis-plus:
  mapper-locations:
     - classpath:mybatis/mapper/*
#  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com/atguigu/admin/bean
#  type-handlers-package: com/atguigu/admin/typehandler
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
 
      

      
    
      
  
    
   #  type : org.springframework.jdbc.core.JdbcTemplate     
  
#  jdbc:
#    template:
#      query-timeout: 3        
      
      
   
# management 是所有actuator的配置
# management.endpoint.端点名.xxxx 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
        include:
        - '*'  # 以web方式暴露所有端点   
  endpoint:
    health:
      show-details: always
 
